version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventless
      POSTGRES_PASSWORD: eventless
      POSTGRES_DB: eventless
      TZ: 'Europe/Zurich'
      PGTZ: 'Europe/Zurich'
